site_name: talk-to-a-file
theme:
  name: material
  search: true
  features:
    - quick-links
    - navigation
    - search
    - toc
    - navigation.tabs
  nav:
    - Home: index.md
    - API:
      - utils: api/utils.md
      - talk: api/talk.md

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
- search
- mkdocstrings